### ISSUE TITLE
libc: reconfigure DNS resolver when network settings change

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1463]
The libc DNS resolver only reads `/etc/resolv.conf`, which is generated automatically if DHCP is used, once when the application is started. If we change the network at runtime, it will still use the first configured nameserver.

**Comment by chelmuth** [comment]
This was fixed by commit 74dcc7a3d57f91fd7382964ac1524ad622dd5f2d from issue #2861.

**Comment by cnuke** [comment]
Well, AFAICT it still just reads the file only once - only the location of the file has changed.

**Comment by chelmuth** [comment]
As this is implemented entirely in the contrib code, I wonder how long running programs in FreeBSD cope with such situations...

**Comment by cnuke** [comment]
That is indeed the question but we still don't have an immediate use-case for the behaviour and probably don't want do fiddle around with libresolv anyway...

(I merely wanted to emphasize that #2861 is not strictly the fix for this issue.)

**Comment by chelmuth** [comment]
For completeness: New versions of the FreeBSD libc implement time-driven configuration reload (see https://github.com/freebsd/freebsd/blob/master/lib/libc/resolv/res_state.c#L105).
