### ISSUE TITLE
Sculpt OS 24.10

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#5356]
Today I have bumped the Sculpt version at staging to 24.10. So the inter-component interfaces are meant to be stable for the release. Let's enter the testing phase and discuss practical issues here.

**Comment by nfeske** [comment]
On the Gen12 Framework, I encountered the following issues:

* The touchpad driver produces a page fault at 0.
* When typing at a certain rate, the most recent character does not appear on the display. I presume that the effect is related to #5347, the driver is sleeping when it shouldn't. Interestingly, I'm unable to observe the issue on the x250. 
* VirtualBox failed to start. The error message features an unholy display size. So the problem might be related to the very recent change in #5353.

**Comment by nfeske** [comment]
> When typing at a certain rate, the most recent character does not appear on the display.

Solved by commit https://github.com/genodelabs/genode/commit/b092b3248972466d5fdfa1f3ae2cd99815a33ca6

**Comment by nfeske** [comment]
> VirtualBox failed to start. The error message features an unholy display size.

There was indeed a problem with the initial mode setting, which is fixed by 648e31e504c397a8d7d140a88f3a798c5d17c33f. However, vbox still fails to start on the Gen12 Framework due to a virtualization-related issue. It works on the x250. @alex-ab way this be related to #5314?

**Comment by nfeske** [comment]
VBox6 on Gen12 Framework:
```
[core] [init -> runtime -> vbox6 -> vbox]   0x40000000 .. 0x4fffffff: stack area[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x30000 .. 0x14afff: ld.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x2b19000 .. 0x2b42fff: egl.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x10e19000 .. 0x10ffffff: libc.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x10d76000 .. 0x10e18fff: vfs.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x2b43000 .. 0x2c29fff: libiconv.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x10d34000 .. 0x10d75fff: libm.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x2c2a000 .. 0x2cc3fff: libyuv.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x2cc4000 .. 0x2d03fff: jpeg.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x2d04000 .. 0x2f81fff: stdcxx.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x2f82000 .. 0x4a6afff: mesa.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x4a6b000 .. 0x4a9afff: expat.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x4a9b000 .. 0x4b26fff: glapi.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x4b27000 .. 0x4b5cfff: libdrm.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x10d15000 .. 0x10d2bfff: vfs_gpu.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x4b5d000 .. 0x4b73fff: zlib.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x4b74000 .. 0x4bf2fff: qemu-usb.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x4bf3000 .. 0x4c49fff: virtualbox6-shaderlib.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x10ce2000 .. 0x10d14fff: vfs_oss.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox] OSS: verbose: 0 play_enabled: 1 min_ofrag_size: 8192 max_ofrag_size: 8192 record_enabled: 1 min_ifrag_size: 8192 max_ifrag_size: 8192 min_sample_rate: 8000 max_sample_rate: 48000 [0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x10ccd000 .. 0x10ce1fff: vfs_pipe.lib.so[0m[0m
[core] [init -> runtime -> vbox6 -> vbox] main     Log created: 2024-10-04T14:52:44.000000000Z[0m
[core] [init -> runtime -> vbox6 -> vbox] main     Process ID:  0 (0x0)[0m
[core] [init -> runtime -> vbox6 -> vbox] main     Parent PID:  -1 (0xffffffff)[0m
[core] [init -> runtime -> vbox6 -> vbox] main     Executable:  /virtualbox6[0m
[core] [init -> runtime -> vbox6 -> vbox] [34mWarning: statfs provides bogus values for '//machine.vdi' (probably a shared folder)[0m[0m
[core] [init -> runtime -> vbox6 -> vbox]   0x4c4a000 .. 0x4c76fff: VBoxSharedClipboard.so[0m[0m
[core]  -> vbox] EMT-0     52 R3     0001  4002-4002        ACPI PM1a Enable[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     53 R3     0001  4004-4004        ACPI PM1a Control[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     54 R3     0001  4008-4008        ACPI PM Timer[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     55 R3     0001  4020-4020        ACPI GPE0 Status[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     56 R3     0001  4021-4021        ACPI GPE0 Enable[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     57 R3     0010  4100-410f        SMBus[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     58 R3     0001  442e-442e        ACPI SMI[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     59 R3     0001  3000-3000        ACPI Debug hex[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     60 R3     0001  3001-3001        ACPI Debug char[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     61 R3     0001  4040-4040        ACPI Battery status index[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     62 R3     0001  4044-4044        ACPI Battery status data[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     63 R3     0001  4048-4048        ACPI system info index[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     64 R3     0001  404c-404c        ACPI system info data[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0     65 R3     0001  4050-4050        ACPI Reset[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    !![0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    !! {irqroute}[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    !![0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    PCI interrupt router at: 00:01:0[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    PIRQA disabled[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    PIRQB -> IRQ0[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    PIRQC -> IRQ0[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    PIRQD -> IRQ0[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    !![0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    !! {lbr}[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    !![0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    HM is not enabled for this VM![0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    !!Assertion Failed!![0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    Expression: HMIsSvmActive(pVM)[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    Location  : /plain/no/genode.git/contrib/virtualbox6-a58000c856a6a838d0da22df8c144a60211b4572/src/virtualbox6/src/VBox/VMM/VMMR3/HM.cpp(3392) void hmR3InfoLbr(PVM, PCDBGFINFOHLP, const ch
[core] ar*)[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    Stack     :[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0    0000000001ab0163[0m
[core] [init -> runtime -> vbox6 -> vbox] EMT-0[0m
[core] [init -> runtime -> vbox6 -> vbox]  35 R3     0001  03ba-03ba[0m
[core] [init -> runtime -> vbox6 -> vbox] !!Assertion Failed!![0m
[core] [init -> runtime -> vbox6 -> vbox] Expression: HMIsSvmActive(pVM)[0m
[core] [init -> runtime -> vbox6 -> vbox] Location  : /plain/no/genode.git/contrib/virtualbox6-a58000c856a6a838d0da22df8c144a60211b4572/src/virtualbox6/src/VBox/VMM/VMMR3/HM.cpp(3392) void hmR3InfoLbr(PVM, PCDBGFINFOHLP, const char*)[0m
[core] [init -> runtime -> vbox6 -> vbox] Stack     :[0m
[core] [init -> runtime -> vbox6 -> vbox] 0000000001ab0163[0m
[core] [init -> runtime -> vbox6 -> vbox] [0m
[core] [34mWarning: unresolvable exception 3, pd 'init -> runtime -> vbox6 -> vbox', thread 'EMT-0', cpu 4, ip=0x1e6c00e sp=0x40ffc300 bp=0x40ffc350 no signal handler[0m
[core] [init -> runtime -> vbox6 -> vbox] [31mError: machine could not enter running state[0m[0m
[kernel] [ 4] Killed EC:0xffffffff81e8d1c0 SC:0xffffffff81d4b040 V:0x21 CR0:0x0 CR3:0x0 CR4:0x1 (IPC Abort)
[core] [31mError: illegal READ at address 0x0 by pager_object: pd='init -> runtime -> vbox6 -> vbox' thread='ep' ip=0x10251f4[0m

```

**Comment by nfeske** [comment]
> I noticed that the text cursor in the menu view (wifi passphrase, text editor in the files section) is always displayed at the left position. 

Fixed by https://github.com/genodelabs/genode/commit/72dc8592272410df5c4569c459f4a99d6c36b984

**Comment by nfeske** [comment]
> However, vbox still fails to start on the Gen12 Framework due to a virtualization-related issue. It works on the x250. @alex-ab way this be related to https://github.com/genodelabs/genode/issues/5314?

False alarm: While switching between 24.04 and my test builds, I missed to copy the NOVA version matching 24.10. With the up-to-date kernel, VBox works just fine on my Gen12 Framework.

**Comment by nfeske** [comment]
When starting the system shell, the following warning appears:
```
[init -> runtime -> system_shell -> /bin/bash -> 1] Warning: sigaltstack using self chosen stack is not supported - stack ptr is ignored !!!
```
As this warning almost always appears in the Sculpt log, we should either find a way to avoid it (supporting the non-supported case) or inform the user more politely, at the very least removing the abundance of exclamation marks.

**Comment by cnuke** [comment]
Commits [76f8f87](https://github.com/cnuke/genode/commit/76f8f87b8366d6e262c1e78de6fb28e59dba5573) and [e3c0870](https://github.com/cnuke/genode/commit/e3c0870a6988071733685ca1b0496e35d0d0f514) address the inconvenience due to the changed defaults regarding WLAN connectivity.

**Comment by ssumpf** [comment]
During testing I experienced 1x1 window sizes for the `system_shell` and `terminal` tools. An investigation showed that a mode-change signal can overwrite the initial-window configuration in case `Gui::Connection::window` returns `Undefined`.  [de46c07](https://github.com/ssumpf/genode/commit/de46c07daed5564d100cc5208db491164f4e738c) is a possible solution for this problem while [b62f260](https://github.com/ssumpf/genode/commit/b62f26075be57b881130d6a851ddfcef12df0e8f) adjusts the cap quota for the terminal tool.

**Comment by cnuke** [comment]
Commit [12d97d3](https://github.com/cnuke/genode-allwinner/commit/12d97d3186781e439aa2ad90e4d4d535354f6f14) fixes the `a64_wifi` driver.

@ssumpf please make sure to use it when testing the *PinePhone*.

**Comment by cnuke** [comment]
* [0b9d3c3](https://github.com/cnuke/genode/commit/0b9d3c3dccd91e1643d9d3f68476740d96b42707) increases the initial CAP quota of the `wifi` driver triggered by Alder Lake systems
* [31f9d41](https://github.com/cnuke/genode/commit/31f9d414a386678abb8a202f23b7a5992de8b82b) remove the generation of an invalid '<network>'
* [40f2b58](https://github.com/cnuke/genode/commit/40f2b58098bf546ce665211f13574c597fb2a7d4) consolidates the `wifi_config` generator snippets
* [e4d2a4d](https://github.com/cnuke/genode/commit/e4d2a4df42f0f9484cf9afac3566f3b1d1ded20b) splits the `explicit_scan` intent
* [e0874ba](https://github.com/cnuke/genode/commit/e0874baa8fbddcdecd1920f3f494ae2ee53b931d) removes the `auto_connect` - this functionality is implicitly provided by adding/removing '<network>' nodes
* [57318b5](https://github.com/cnuke/genode-imx/commit/57318b52a33e1f8fc9544d58fe281f797f8092fc) **imx** .inc
* [57318b5](https://github.com/cnuke/genode-imx/commit/57318b52a33e1f8fc9544d58fe281f797f8092fc) **imx** auto_connect
* [b057aab](https://github.com/cnuke/genode-allwinner/commit/b057aab015d2414e0c163976a1eecda606eb6b73) **allwinner** .inc
* [0a991ed](https://github.com/cnuke/genode-allwinner/commit/0a991ed73dfd200c5b5de704f6ee105ba77ef53a) **allwinner** auto_connect

**Comment by jschlatow** [comment]
Commit 9f9e539 updates the goa_testbed preset. The corresponding archives are now available on my depot for x86_64 and arm_v8a.

**Comment by cnuke** [comment]
Commit [af1ab18](https://github.com/cnuke/genode-world/commit/af1ab187039bbbf4ef84f0280bd0836edc5ac769) restores the intended behavior of considering the initial mode specified via the configuration in case the window size is undefined in the SDL2 library.

Note: I have not tested all SDL2 based components but just a few of my own and SDL1 probably requires the same treatment.

**Comment by cnuke** [comment]
The following commits realise mouse-grabbing with SDL2 components.

* [cc97428](https://github.com/cnuke/genode/commit/cc9742883ce2188e6b407d02f986b01e487b1129) adapts the `window_layouter` configuration
* [b0e77e0](https://github.com/cnuke/genode-world/commit/b0e77e0216e71f840c007613df7409387d43c45c) adds enabling the *exclusive* input mode to SDL2 by configuring `mouse_grab` in the component's configuration

So far the feature was only tested with some SDL2 games that already handle absolute vs. relative motion events transparently, so YMMV.

**Comment by jschlatow** [comment]
@nfeske I'm trying to adapt the screenshot component to the capture-session changes. I noticed that `Capture::Connection::screen_size()` returns an invalid area if the client has not created a capture buffer yet because, I believe, the method always returns the bounding box of the current capture session. The former behaviour was to return the bounding box of all capture sessions. I am particularly wondering about the use of `Rect::intersect` in `screen_size()`: The view stack bounding box is computed as the bounding box of all capture sessions, hence the below code is, imho, the same as `return bounding_box().area`. Am I missing something?

https://github.com/genodelabs/genode/blob/61c970635313d25a834512a4b239694332632b2f/repos/os/src/server/nitpicker/capture_session.h#L197-L200

**Comment by cnuke** [comment]
Commit [313a105](https://github.com/cnuke/genode/commit/313a10513dbd742882b27beeea74d9913378a791) addresses the problem with the small terminal size that @ssumpf already encountered (see https://github.com/genodelabs/genode/issues/5356#issuecomment-2397592040) but employs the pattern I used with SDL2.

**Comment by cnuke** [comment]
I noticed what appear to be *graphical glitches* while resizing the terminal window. Parts of the terminal content are shown at the right side and at the bottom, clearly visible when resizing quickly.

**Comment by jschlatow** [comment]
> Commit [9f9e539](https://github.com/genodelabs/genode/commit/9f9e539d9cc3de4ab5b08e30ddd9fff227694a30) updates the goa_testbed preset. The corresponding archives are now available on my depot for x86_64 and arm_v8a.

I forgot removing the _drv suffix from the mesa_gpu route and therefore updated the goa_testbed archive version. The new commit is c28d3a1. This also replaces the Audio_in/out routes with Record/Play, which we've apparently missed so far.

**Comment by jschlatow** [comment]
On my x260, mesa_gears depleted its RAM quota. Commit e45ab67 adjusts this.

**Comment by jschlatow** [comment]
> Commit [5980225](https://github.com/cnuke/genode-world/commit/5980225f99330391afef89511c482ad140656005) restores handling of key press events, which regressed with genodelabs/genode-world#386 and thus should be treated as _WIP_.
> 
> @jschlatow could you please check if `sdl_vnc` still exhibits the problems that prompted your adaptions as I to some degree reverted them. Sorry for noticing the regression with such a delay (TBH I have not excerised SDL2 components lately).

The commit restores the unmapped keysym warning, the key input still works, though. Thus, I'll simply remove the warning from the VNC server.

By the way, I had to increase the cap quota in sdl_vnc (see commit jschlatow/genode-world@dc8163c).

**Comment by cnuke** [comment]
> The commit restores the unmapped keysym warning, the key input still works, though. Thus, I'll simply remove the warning from the VNC server.

Thank you for looking into it - for now patching it sounds reasonable. When we overhaul the SDL2 port finding a different solution would be sensible.

**Comment by chelmuth** [comment]
I tried to gather all commits referenced in this issue since last Tuesday. Please check if I missed something.

**Comment by chelmuth** [comment]
> @chelmuth Have you considered [e45ab67](https://github.com/genodelabs/genode/commit/e45ab67f664e04fda79b9f36bc6e8581f4f18c9e)?

Missed that one, merged just now.

**Comment by cnuke** [comment]
> I tried to gather all commits referenced in this issue since last Tuesday. Please check if I missed something.

You caught all my commits but apparently used the ones from my working branch rather than the specific topic branches (the content is the same but the commit contains a commit message and reference to this issue in the later case).

**Comment by jschlatow** [comment]
@cproc I noticed that the jemalloc versions of Falkon and Morph browser get quickly stuck in a RAM request. This typically occurs after opening the second or third website after having played a youtube video. This does not seem to occur with the non-jemalloc versions.

Moreover, I am unable to sign into github. The "sign in" button has no effect in either version of Falkon/Morph.

**Comment by jschlatow** [comment]
> * The usb_webcam, test-capture test does not produce any picture on the x250. Even though I added a device policy to /config/usb, the log shows no lifesign of the webcam driver.

Same with the x230, x260 and t490s as well as my external webcam.

**Comment by cnuke** [comment]
Commit [449694a](https://github.com/cnuke/genode/commit/449694a8b56529aa17fd05e21b5442533c46d576) mitigates a performance regression with Realtek network devices.

As @alex-ab noticed the `pc_nic` driver behaves unexpectedly (the throughput is low) on his machine using a Realtek device. I could reproduce the problem running *netperf_lwip* where staging produces around 0.1(!) MBit/s while the commit of the driver before the update to 6.6.47 gets around 500 MBit/s. I diffed the old and new driver version and one change that caught my eye was the activation of IRQ coalescing. When removing the function call the driver performs as before the update. I have not investigated why enabling the feature apparently leads to performance issues though.

**Comment by chelmuth** [comment]
> You caught all my commits but apparently used the ones from my working branch rather than the specific topic branches (the content is the same but the commit contains a commit message and reference to this issue in the later case).

I did not notice that you're maintaining two flavors of commits. For me, it's okay to lose the reference to this issue. Do you agree?

**Comment by chelmuth** [comment]
> As @alex-ab noticed the `pc_nic` driver behaves unexpectedly (the throughput is low) on his machine using a Realtek device. I could reproduce the problem running _netperf_lwip_ where staging produces around 0.1(!) MBit/s while the commit of the driver before the update to 6.6.47 gets around 500 MBit/s. I diffed the old and new driver version and one change that caught my eye was the activation of IRQ coalescing. When removing the function call the driver performs as before the update. I have not investigated why enabling the feature apparently leads to performance issues though.

Could this be related to the behavior discovered in #3939? May you open a dedicated issue for this instance?

**Comment by cnuke** [comment]
> > You caught all my commits but apparently used the ones from my working branch rather than the specific topic branches (the content is the same but the commit contains a commit message and reference to this issue in the later case).
> 
> I did not notice that you're maintaining two flavors of commits.

I normally create a specific topic branch (*issue#xxx…*) that contains a proper commit message and the reference to the github issue and is the commit that I cite in the issue's comment after the fact. Sometimes I cherry-pick that commit to a WIP branch and deliberately remove the reference to no pollute the github issue's history.  

> For me, it's okay to lose the reference to this issue. Do you agree?

It is fine for me.

**Comment by cnuke** [comment]
> > As @alex-ab noticed the `pc_nic` driver behaves unexpectedly (the throughput is low) on his machine using a Realtek device. I could reproduce the problem running _netperf_lwip_ where staging produces around 0.1(!) MBit/s while the commit of the driver before the update to 6.6.47 gets around 500 MBit/s. I diffed the old and new driver version and one change that caught my eye was the activation of IRQ coalescing. When removing the function call the driver performs as before the update. I have not investigated why enabling the feature apparently leads to performance issues though.
> 
> Could this be related to the behavior discovered in #3939?

It could but since I do not know the iPXE driver operates the device I can only speculate. 

> May you open a dedicated issue for this instance?

Of course.

**Comment by jschlatow** [comment]
> @cproc I noticed that the jemalloc versions of Falkon and Morph browser get quickly stuck in a RAM request. This typically occurs after opening the second or third website after having played a youtube video. This does not seem to occur with the non-jemalloc versions.

I think jschlatow/genode-world@ca0760b is a good solution for letting users adapt to higher RAM requirements of the browser. Note, this does not change the default RAM quota specified by the runtime but let's the user effectively increase the quota in a launcher file.

**Comment by jschlatow** [comment]
> The x250 seems to mostly work fine [...]. Wakeup from standby does not work

Wakeup does not work on my x230, x260 or t490s either.

**Comment by jschlatow** [comment]
> > The x250 seems to mostly work fine [...]. Wakeup from standby does not work
> 
> Wakeup does not work on my x230, x260 or t490s either.

It does work on base-hw, though (tested on x230 and x260).

**Comment by skalk** [comment]
Commit 9c32d7d addresses the record_play_mixer instead of the oldfashioned audio mixer within the sculpt default index file. Now, it happens that the old mixer is shown in the index but not available, because the new one is part of the distribution packages.

**Comment by alex-ab** [comment]
> > When typing at a certain rate, the most recent character does not appear on the display.
> 
> Solved by commit [b092b32](https://github.com/genodelabs/genode/commit/b092b3248972466d5fdfa1f3ae2cd99815a33ca6)

The issue still happens to @chelmuth and me. Commit 5fd5c06bfb49a2567754321d11f5e82c69ae33f5 fixes the wakeup/sleep handling for me. @chelmuth: please consider for staging

**Comment by cproc** [comment]
> I think [jschlatow/genode-world@ca0760b](https://github.com/jschlatow/genode-world/commit/ca0760b) is a good solution for letting users adapt to higher RAM requirements of the browser. Note, this does not change the default RAM quota specified by the runtime but let's the user effectively increase the quota in a launcher file.

Thanks, I published new browser packages with this commit applied.

**Comment by jschlatow** [comment]
I gave Sculpt 24.10 with base-hw a spin on the x230 and x260 and made the following observations:

- The UI feels much faster on the x230 (i5) than the x260 (i7). The latter has a very sluggish feel, when depot download is in progress whereas the x230 still feels very responsive. Yet, this is not a regression as I can reproduce the same effect with 24.04. I suspected the display resolution (1366x768 on the x230 vs 1920x1080 on the x260) but this has no significant effect on 24.04. **On 24.10, I'm not able to change the display resolution on the x260 by editing _/config/fb_.**
- After a few minutes running 24.10 on the x230, the mouse pointer freezes. The pointer coordinates still seem to be updated, though, as I'm still seeing hover effects when moving the mouse.

**Comment by cnuke** [comment]
* [665d3ff](https://github.com/cnuke/genode/commit/665d3ffcae5ac9c654b862ffc2556069488a9da6) straightens out the invalid `<network/>` entry check (as was trigger by the *PinePhone* see next commit)
* [754331e](https://github.com/cnuke/genode/commit/754331e5a691b09d74621aeb94e05190c87c8fb5) changes the default wifi config to provide the exemplary `<network/>` node via a comment.

In case someone is testing the *PinePhone*, sometimes the wifi GUI gets stuck displaying the *scanning* label although fresh scan results are available because it seems to thing the AP selection list is already hovered. Leaving and entering the *Network* section works around this problem.

**Comment by alex-ab** [comment]
> > > When typing at a certain rate, the most recent character does not appear on the display.
> > 
> > 
> > Solved by commit [b092b32](https://github.com/genodelabs/genode/commit/b092b3248972466d5fdfa1f3ae2cd99815a33ca6)
> 
> The issue still happens to @chelmuth and me. Commit [5fd5c06](https://github.com/genodelabs/genode/commit/5fd5c06bfb49a2567754321d11f5e82c69ae33f5) fixes the wakeup/sleep handling for me. @chelmuth: please consider for staging

After @chelmuth reported that the issue still happens to him, I instrumented the GUI stack down to nitpicker. After some investigation, it turns out that the leitzentrale -> nitpicker sometimes does not report content changes immediately if the changes are too close together (smaller 40ms). If no further change happens, or not close in a timely manner, the output seems too "hang" and appear quite late (up to 2s seen in inspect window in Leitzentrale). Commit 13d72ba31f16224dd7b7f77399aa3dfc2ec6b115 addresses the issue and make the symptom go away for me. @chelmuth: please give it a try

**Comment by alex-ab** [comment]
I published before the weekend a new sculpt test image based on staging + 37e03d1131c16010dafc03ebca63a65f456bf713 and + 13d72ba31f16224dd7b7f77399aa3dfc2ec6b115 (acked by @chelmuth). @cproc: I assume 10-16 is the current falkon version, and not the 21.10 (date 10-13).

**Comment by cproc** [comment]
> @cproc: I assume 10-16 is the current falkon version, and not the 21.10 (date 10-13).

yes, 10-16 is the current version

**Comment by trimpim** [comment]
On my Lenovo T14 I got the following error:

```
[runtime -> wifi] Error: Function unregister_handler_proc not implemented yet
```

This happened when I started the WiFi driver, realized that I forgot to copy the WiFi-configuration, stopped the driver, copied the config to `/config/managed` (from the 24.04 release config) and started the driver again.

This doesn't happen, if I start/stop the driver multiple times in a row when a configuration is present.

**Comment by trimpim** [comment]
@cproc sure

**Comment by atopia** [comment]
> On my Lenovo T14 I got the following error:
> 
> ```
> [runtime -> wifi] Error: Function unregister_handler_proc not implemented yet
> ```

I just hit the same path on 24.04 on the X1 Nano (with wifi configuration). I'm not 100% sure but I believe I had accidentally booted into native Linux on the previous boot instead of selecting the 20.04 boot entry. Before that I had sucessfully run the driver testing 24.10 (also with a wifi configuration).
 @cnuke I'll email you the corresponding log to look at after your vacation.

**Comment by chelmuth** [comment]
>     * The usb_webcam, test-capture test does not produce any picture on the x250. Even though I added a device policy to /config/usb, the log shows no lifesign of the webcam driver.

I adapted usb_webcam/test-capture to the changes in capture/GUI sessions with 6cbf55916a0229be2855616171abbb5fd2a5f86a. @nfeske @jschlatow please give it a spin.

**Comment by nfeske** [comment]
> If no further change happens, or not close in a timely manner, the output seems too "hang" and appear quite late (up to 2s seen in inspect window in Leitzentrale)

@alex-ab commit https://github.com/genodelabs/genode/commit/cc12816d871d92b878a0b48eeaf71321543bba63 should fix this issue. BTW, the 2s come from the log view that is updated at that interval, even when located off-screen.

**Comment by nfeske** [comment]
@skalk and @chelmuth, commit https://github.com/genodelabs/genode/commit/09ed07b89ed2e71ba81228e2b7cdf6829c9b2b5a should address the left-over pixels when closing the popup view, as you reported.

**Comment by cproc** [comment]
I get the following error on the PinePhone with the `gpu test` preset (and also with my local WIP morph browser update):

```
[init -> runtime -> glmark2] Warning: ignoring unsupported RTLD_GLOBAL in dlopen()
[init -> runtime -> glmark2] libEGL warning: MESA-LOADER: failed to retrieve device information
[init -> runtime -> glmark2] 
[init -> runtime -> glmark2] Error: no plugin found for fstat(10044)
[init -> runtime -> glmark2] Error: Uncaught exception of type 'Genode::Attached_dataspace::Region_conflict'
[init -> runtime -> glmark2] Warning: abort called - thread: ep
```

**Comment by ssumpf** [comment]
@cproc: Could you try out [b3a416c](https://github.com/ssumpf/genode/commit/b3a416c86f99a6934578a5211b8a3172675a7417) from my staging branch and see if this fixes  3D for you too?

**Comment by cproc** [comment]
> @cproc: Could you try out [b3a416c](https://github.com/ssumpf/genode/commit/b3a416c86f99a6934578a5211b8a3172675a7417) from my staging branch and see if this fixes 3D for you too?

Yes, that fixed it.

Now there's another problem with the Morph browser on the PinePhone: when I load `genodians.org` the following error occurs:

```
[init -> runtime -> morph_browser -> morph-browser] Error: LD: jump slot relocation failed for symbol: 'util_format_unpack_description_neon'
[init -> runtime -> morph_browser -> morph-browser] Error: Uncaught exception of type 'Linker::Not_found'
[init -> runtime -> morph_browser -> morph-browser] Warning: abort called - thread: QSGRenderThread.24
```

The following change in mesa made the error go away, but it's probably not the correct fix:

```
diff --git a/src/util/format/u_format.c b/src/util/format/u_format.c
index 30dd65e..0ef6972 100644
--- a/src/util/format/u_format.c
+++ b/src/util/format/u_format.c
@@ -1221,7 +1221,7 @@ static void
 util_format_unpack_table_init(void)
 {
    for (enum pipe_format format = PIPE_FORMAT_NONE; format < PIPE_FORMAT_COUNT; format++) {
-#if (DETECT_ARCH_AARCH64 || DETECT_ARCH_ARM) && !defined(NO_FORMAT_ASM) && !defined(__SOFTFP__)
+#if (DETECT_ARCH_AARCH64 || DETECT_ARCH_ARM) && !defined(NO_FORMAT_ASM) && !defined(__SOFTFP__) && 0
       const struct util_format_unpack_description *unpack = util_format_unpack_description_neon(format);
       if (unpack) {
          util_format_unpack_table[format] = unpack;
```

I can try to get a backtrace to find a simpler test case to trigger the error if that helps.

**Comment by atopia** [comment]
> > On my Lenovo T14 I got the following error:
> > ```
> > [runtime -> wifi] Error: Function unregister_handler_proc not implemented yet
> > ```

It seems I can reproduce this reliably by rebooting from Linux to Genode 24.04 but when rebooting from Linux to 24.10 the error didn't occur (at least in the one test I did).

**Comment by atopia** [comment]
@chelmuth please consider f1a8d67aecbb1d1c606f534caddd21987858e290, 56ffad1bc8d3e81b9b18df96693c406f2375f13f, and 90f26b1591a3f4cc9a45b036bb6719030f6196f1 for staging.

**Comment by chelmuth** [comment]
> @cproc: Could you try out [b3a416c](https://github.com/ssumpf/genode/commit/b3a416c86f99a6934578a5211b8a3172675a7417) from my staging branch and see if this fixes 3D for you too?

@ssumpf I revealed the mystery behind this obviously dubious fix: libdrm contains ioctl implementations for both lima and etnaviv which both implement `Gpu::Vram::mmap()` in different `Gpu::Vram` classes... I do not know why the linker does not whine about the duplicates but these must be resolved. I suggest do move the whole ioctl implementations into `namespace Etnaviv` resp. `namespace Lima`.

**Comment by chelmuth** [comment]
> I do not know why the linker does not whine about the duplicates but these must be resolved. 

It's the *one-definition rule* of C++ that bites us: If a member function is defined in the class body, the compiler must enable the linker to decide which instance of the function ends up in the final object. Therefore, these member-function symbols are marked *weak* and no linker error is emitted.

**Comment by ssumpf** [comment]
> ```
> [init -> runtime -> morph_browser -> morph-browser] Error: LD: jump slot relocation failed for symbol: 'util_format_unpack_description_neon'
> [init -> runtime -> morph_browser -> morph-browser] Error: Uncaught exception of type 'Linker::Not_found'
> [init -> runtime -> morph_browser -> morph-browser] Warning: abort called - thread: QSGRenderThread.24
> ```
@cproc: looks like `src/util/format/u_format_unpack_neon.c` needs to be added to _libports/src/lib/mesa/files.list_ and _libports/lib/mk/mesa.inc_ (SRC_C)

**Comment by atopia** [comment]
@nfeske Please have a look at 42c61218c7 as a suggested fix for the runtime_view issue. The fix solves the issue for me (4k screen, mirrored).

**Comment by cproc** [comment]
> @cproc: looks like `src/util/format/u_format_unpack_neon.c` needs to be added to _libports/src/lib/mesa/files.list_ and _libports/lib/mk/mesa.inc_ (SRC_C)

Yes, that solved the problem. Fixed by 05c692f.

**Comment by cproc** [comment]
Another problem with the Morph Browser on the PinePhone is that the Qt window area doesn't end at the top of the on-screen keyboard anymore. I see a window area of 720x1440 read from the GUI info.

**Comment by nfeske** [comment]
> @cnuke: I noticed what appear to be graphical glitches while resizing the terminal window. Parts of the terminal content are shown at the right side and at the bottom, clearly visible when resizing quickly.

Thanks for reporting! Fixed by 342155320c3fa6d374d704ab3cc20a227b7da4ce

**Comment by nfeske** [comment]
@cproc may you give 3501a616e9e952855d87882795ea467512a28ab2 a try?

**Comment by ssumpf** [comment]
@chelmuth: [d506d2b](https://github.com/ssumpf/genode/commit/d506d2be7e14a5eef2858f89ac07242e9295fdb8) moves the `Gpu::Vram` implementations for Lima/Vivante into separate namespaces. Thanks for finding out.

**Comment by cproc** [comment]
> @cproc may you give [3501a61](https://github.com/genodelabs/genode/commit/3501a616e9e952855d87882795ea467512a28ab2) a try?

Yes, that solved the problem.

**Comment by atopia** [comment]
@nfeske [73d23e0](https://github.com/atopia/genode/commit/73d23e0dec4bf704efc4e03ba8f42c6c07870776) adds a depot user for myself.

**Comment by cproc** [comment]
I'm trying to run Sculpt 24.10 on the i.MX 8 EVK board (loaded via TFTP), but haven't got it working yet.

This is my build command:

```
make KERNEL=hw BOARD=imx8q_evk LOG=core run/sculpt
```

and this is the Genode log output:

```
Genode 24.08-161-gb337deb5b4 <local changes>
2774 MiB RAM and 64533 caps assigned to init
[init] Warning: runtime: configured RAM exceeds available RAM, proceed with 2399143456
[init -> runtime] parent provides
[init -> runtime]   service "ROM"
[init -> runtime]   service "PD"
[init -> runtime]   service "RM"
[init -> runtime]   service "CPU"
[init -> runtime]   service "LOG"
[init -> runtime]   service "IO_MEM"
[init -> runtime]   service "IO_PORT"
[init -> runtime]   service "IRQ"
[init -> runtime]   service "Gui"
[init -> runtime]   service "Timer"
[init -> runtime]   service "Block"
[init -> runtime]   service "Report"
[init -> runtime]   service "Platform"
[init -> runtime] monitor ready
[init -> runtime] parent provides
[init -> runtime]   service "VM"
[init -> runtime]   service "Usb"
[init -> runtime]   service "File_system"
[init -> runtime]   service "Rtc"
[init -> runtime]   service "TRACE"
[init -> runtime]   service "Event"
[init -> runtime]   service "Capture"
[init -> runtime]   service "Gpu"
[init -> runtime]   service "Pin_state"
[init -> runtime]   service "Pin_control"
[init -> runtime]   service "I2c"
[init -> runtime]   service "Terminal"
[init -> runtime] child "runtime_view"
[init -> runtime]   RAM quota:  53000K
[init -> runtime]   cap quota:  296
[init -> runtime]   ELF binary: menu_view
[init -> runtime]   priority:   1
[init -> runtime] child "ram_fs"
[init -> runtime]   RAM quota:  776K
[init -> runtime]   cap quota:  266
[init -> runtime]   ELF binary: vfs
[init -> runtime]   priority:   1
[init -> runtime]   provides service File_system
[init -> runtime] child "ram_fs" announces service "File_system"
```

Nothing to see on the screen. Any ideas?

**Comment by ssumpf** [comment]
@cproc: There is no support in the sculpt_manager for imx8q_evk. So no driver will be started. I have a commit somewhere for testing.

**Comment by ssumpf** [comment]
@cproc: You can use [7f0a3b0](https://github.com/ssumpf/genode/commit/7f0a3b08c32c5058f9cc5ac4a6df1be2bafa6548) from my linux-imx-6.6-update branch for testing on the evk.

**Comment by cproc** [comment]
> @cproc: You can use [7f0a3b0](https://github.com/ssumpf/genode/commit/7f0a3b08c32c5058f9cc5ac4a6df1be2bafa6548) from my linux-imx-6.6-update branch for testing on the evk.

With this commit I get a bit more output:

```
Genode 24.08-161-gb337deb5b4 <local changes>
2774 MiB RAM and 64533 caps assigned to init
[init] Warning: runtime: configured RAM exceeds available RAM, proceed with 2399143456
[init -> runtime] parent provides
[init -> runtime]   service "ROM"
[init -> runtime]   service "PD"
[init -> runtime]   service "RM"
[init -> runtime]   service "CPU"
[init -> runtime]   service "LOG"
[init -> runtime]   service "IO_MEM"
[init -> runtime]   service "IO_PORT"
[init -> runtime]   service "IRQ"
[init -> runtime]   service "Gui"
[init -> runtime]   service "Timer"
[init -> runtime]   service "Block"
[init -> runtime]   service "Report"
[init -> runtime]   service "Platform"
[init -> runtime] monitor ready
[init -> runtime] parent provides
[init -> runtime]   service "VM"
[init -> runtime]   service "Usb"
[init -> runtime]   service "File_system"
[init -> runtime]   service "Rtc"
[init -> runtime]   service "TRACE"
[init -> runtime]   service "Event"
[init -> runtime]   service "Capture"
[init -> runtime]   service "Gpu"
[init -> runtime]   service "Pin_state"
[init -> runtime]   service "Pin_control"
[init -> runtime]   service "I2c"
[init -> runtime]   service "Terminal"
[init -> runtime] child "fb"
[init -> runtime]   RAM quota:  16136K
[init -> runtime]   cap quota:  216
[init -> runtime]   ELF binary: fb
[init -> runtime]   priority:   1
[init -> runtime] child "usb"
[init -> runtime]   RAM quota:  16136K
[init -> runtime]   cap quota:  166
[init -> runtime]   ELF binary: usb
[init -> runtime]   priority:   1
[init -> runtime]   provides service Usb
[init -> runtime] child "runtime_view"
[init -> runtime]   RAM quota:  53000K
[init -> runtime]   cap quota:  296
[init -> runtime]   ELF binary: menu_view
[init -> runtime]   priority:   1
[init -> runtime] child "ram_fs"
[init -> runtime]   RAM quota:  776K
[init -> runtime]   cap quota:  266
[init -> runtime]   ELF binary: vfs
[init -> runtime]   priority:   1
[init -> runtime]   provides service File_system
[init -> runtime] Error: fb: environment ROM session denied (label="fb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: fb: environment ROM session denied (label="fb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: fb: environment ROM session denied (label="fb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: fb: environment ROM session denied (label="fb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: fb: environment ROM session denied (label="fb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: fb: environment ROM session denied (label="fb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: fb: environment ROM session denied (label="fb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: fb: environment ROM session denied (label="fb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: fb: environment ROM session denied (label="fb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: fb: environment ROM session denied (label="fb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: usb: environment ROM session denied (label="usb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: usb: environment ROM session denied (label="usb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: usb: environment ROM session denied (label="usb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: usb: environment ROM session denied (label="usb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: usb: environment ROM session denied (label="usb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: usb: environment ROM session denied (label="usb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: usb: environment ROM session denied (label="usb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: usb: environment ROM session denied (label="usb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: usb: environment ROM session denied (label="usb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] Error: usb: environment ROM session denied (label="usb", ram_quota=6144, cap_quota=3, diag=0)
[init -> runtime] child "ram_fs" announces service "File_system"
```

**Comment by ssumpf** [comment]
@cproc: You will need 44e5b4a4bb586458e0a1abbde6d05850344fbc01 this one also. I thought this made to staging.

**Comment by cproc** [comment]
> @cproc: You will need [44e5b4a](https://github.com/genodelabs/genode/commit/44e5b4a4bb586458e0a1abbde6d05850344fbc01) this one also. I thought this made to staging.

Thanks, it's working now.

**Comment by chelmuth** [comment]
> @cproc: You will need [44e5b4a](https://github.com/genodelabs/genode/commit/44e5b4a4bb586458e0a1abbde6d05850344fbc01) this one also. I thought this made to staging.

Should this remark be read as merge request? What about the EVK support commit?

**Comment by ssumpf** [comment]
@chelmuth: No, I just forgot about it. We can look into this when more boards get adapted by the sculpt_manager.

**Comment by ssumpf** [comment]
[6096536](https://github.com/ssumpf/genode-world/commit/609653608fadcc768412310901507bf3f8c47991) fixes the ubuntu_ui_toolkit meta packet in world.

**Comment by nfeske** [comment]
With commit 3e6f465344f4f9243ab7503ff0a80c8ae6d52398 (on staging), the intel framebuffer driver can be configured in the component graph.

**Comment by nfeske** [comment]
With the commits of issue #5370 (on staging), panoramic scenarios can now be interactively configured by de-selecting the "=" button between the connectors, and by using the "swap" button to change the horizontal order. The leitzentrale is placed always at the display hovered by the pointer. So one can take the leitzentrale GUI from one display to another by merely moving the mouse. More importantly, this ensures that the entirety of the administrative user interface remains always accessible.

**Comment by cnuke** [comment]
@trimpim @atopia Your logs point to a problem with newer integrated *CNVi* Intel wireless devices where restarting the driver or warm-booting from Linux (that was “fixed” on certain machines by disabling MSI/MSI-X via `pci_decode` for the device IIRC) can render the device unusable. It could be that it happens more frequently now after the latest driver update but should have been there all along. From my limited testing it seems that you can get away with restarting the driver when you were already connected to a network but if you were not connected or are currently in the scanning phase most of the time you get the `probe failed` error or fail to interact with the firmware until you power-cycle the machine.

Unfortunately I don't have any ideas on how to solve this problem.

**Comment by nfeske** [comment]
@cnuke, may you give 3b80f661e1caf13e856990544997ef3ad77664d1 a try?

**Comment by cproc** [comment]
Commit ced9019 updates the Falkon preset with the latest pkg version which includes the mesa NEON fix (f997336).

**Comment by chelmuth** [comment]
While changing the order of panorama captures/displays pc_intel_fb entered `Error: Function i915_gem_evict_for_node not implemented yet!`. Do you see any chance to prevent this with limited effort before the release? After the automatic restart the driver worked without flaw.

**Comment by chelmuth** [comment]
Plugging/unplugging one display in a constellation of three displays (mode set to 1920x1080 on all three) lead to two unexpected effects.

- pc_intel_fb: fb_client_hotplug: error on modeset commit -28 - ENOSPC
- a panorama configuration of 7680x1080 with the third display at xpos=5760 (which leaves a 1920 pixel hole at 3840)

**Comment by alex-ab** [comment]
> Plugging/unplugging one display in a constellation of three displays (mode set to 1920x1080 on all three) lead to two unexpected effects.
> 
>     * pc_intel_fb: fb_client_hotplug: error on modeset commit -28 - ENOSPC which may be okay but was followed by `Error: illegal READ at address 0x0 by pager_object: pd='init -> runtime -> intel_fb' thread='ep' ip=0x11f63e2`
> 
>     * a panorama configuration of 7680x1080 with the third display at xpos=5760 (which leaves a 1920 pixel hole at 3840)

I have to guess: with the changes at the gpu driver, the intel display driver _really_ only uses 64M of the aperature, which the ENOSPC hints for. (have to check where it originates). We may have to increase the configuration at the GPU driver from 64M to something more sensible as test

**Comment by nfeske** [comment]
@cnuke, 5b7bb946fad70bbf21e6be0bfba9bfcf2e8e5df7 clamps the x and y position independently.

**Comment by cnuke** [comment]
> @cnuke, [5b7bb94](https://github.com/genodelabs/genode/commit/5b7bb946fad70bbf21e6be0bfba9bfcf2e8e5df7) clamps the x and y position independently.

Thanks, works as advertised :+1:.

**Comment by atopia** [comment]
I'm able to reliably loose the pointer off-screen with current staging.
Steps to reproduce with two screens with a small and a big resolution:
1. copy `/config/managed/fb` to `/config/fb`
2. in `/config/fb`, move the bigger screen / connector first in the `<merge>` node and save, triggering expanding the capture session to the big resolution
3. move the pointer in an area outside of the small screen
4. in `/config/fb`, move the small screen back to the first row and save.

Outcome: the pointer is off-screen and even moving it into the right direction doesn't bring it back on-screen.

When undoing the move (i.e. moving the big connector back to the first row) and saving, the pointer is again visible at the out-of-screen location and can be moved from there.

**Comment by atopia** [comment]
The restriction of the virtual resolution via `/config/fb` does not have an effect, i.e. with
```
<config max_width="3840" max_height="2160" width="1024" height="768" system="yes">
	<report connectors="yes"/>
	<merge width="2160" height="1350" name="DP-3">
		<connector name="DP-3" width="3840" height="2160" hz="60" mode="1"/>
		<connector name="eDP-1" width="2160" height="1350" hz="60" brightness="69" mode="1"/>
	</merge>
</config>
```
I still end up with a 4k desktop.

**Comment by nfeske** [comment]
> @atopia: I'm able to reliably loose the pointer off-screen with current staging.

Thanks for reporting. I'm able to reproduce it. Investigating...

**Comment by chelmuth** [comment]
> I still end up with a 4k desktop.

The panorama is configured via the nitpicker `<capture>` config node (*/config/managed/nitpicker* resp. */config/nitpicker*) and reflected in */report/nitpicker/panorama*.

**Comment by atopia** [comment]
OK. Then I still don't understand how changing the setting is supposed to manifest, but I can ask someone to explain in person after the release.

> https://github.com/genodelabs/genode/blob/61c970635313d25a834512a4b239694332632b2f/repos/pc/src/driver/framebuffer/intel/pc/README#L118-L126

**Comment by nfeske** [comment]
@atopia 850294ee9f05713858bc0c25de7118c50c48d996 should solve the pointer problem. Can you give it a try?

**Comment by atopia** [comment]
@nfeske Thanks a lot, the commit solves the problem!

**Comment by atopia** [comment]
I haven't been able to pin down why it happens in some circumstances and not others, but occasionally *wm* will flood the log with messages like
```
[runtime] child "wm" requests resources: ram_quota=7519400
```
This has happened twice so far, last right at the start on a system that is pre-configured to a mirrored 4k display resolution via `/config/fb` and starting `vbox6-block` and `system_shell` via `/config/deploy`.

I've adjusted the RAM quota in [wm: adjust RAM quota for high-resolution displays](https://github.com/atopia/genode/commit/f2967e0f0851db9a6ea233c50aa17a7baf5ca819)
[f2967e0](https://github.com/atopia/genode/commit/f2967e0f0851db9a6ea233c50aa17a7baf5ca819). Feel free to pull to prevent wm filling up the log in such scenarios or leave out if you feel that the cause needs to be investigated more thoroughly.

**Comment by atopia** [comment]
This is probably more for a future enhancement, but I'm not sure where else to note this:
When using two discrete displays, moving the pointer from one screen with a system_shell / terminal window to the other screen causes the terminal's font to adapt to the changed DPI, even though the terminal window itself is not moved.

**Comment by nfeske** [comment]
> occasionally wm will flood the log with messages like

This has been discussed (and fixed). The fix is not present in the pkgs published so far.

> screen causes the terminal's font to adapt to the changed DPI, even though the terminal window itself is not moved

We noticed this as well. It is surprising but logical. There is only one global font configuration, which depends on the vertical resolution of the leitzentrale. When moving the leitzentrale from one display to another, the font configuration is adjusted. As the font configuration is global, all apps using the fonts_fs respond. You can fix this problem for you by copying a preferred state of /config/managed/fonts to /config, which suppresses the dynamic font reconfiguration.

**Comment by atopia** [comment]
I see. Thanks for the quick explanation!

**Comment by nfeske** [comment]
Commit https://github.com/genodelabs/genode/commit/77e4c7eddbe367b7a76914b3149231c01491d870 updates the documentation.

Reviews of the added text would be very much appreciated.

**Comment by ssumpf** [comment]
> Reviews of the added text would be very much appreciated.

@nfeske: 98659b6 are my suggestions.

**Comment by atopia** [comment]
I pushed my review to 16a600e2b2d08 but I feel this time my changes are merely matter-of-preference, the README is perfectly fine without my changes.

**Comment by nfeske** [comment]
Released today.

**Comment by atopia** [comment]
@nfeske please add [38ef166](https://github.com/atopia/genode/commit/38ef16624d630cfb4d0a4c7a9810c3915259d365) and [edf23d1](https://github.com/atopia/genode/commit/edf23d1458d7ee16eabf3be72d99330f7687492a) to staging.

**Comment by nfeske** [comment]
Thanks. Merged to staging.
